### PR TITLE
Added integration test

### PR DESCRIPTION
**Pull request by ignoreintuition**

### CODE REVIEW

**Comment by debasishbsws** [comment]
Could you please add the scripts for the testing in `package.json`

**Comment by Flanker-shyam** [comment]
routes/movieRoute file's extension got updated to routes/movieRoute.js , kindly prefer the updated codes and make your PR. Thankyou.

**Comment by ignoreintuition** [comment]
Added script to the package.json to run tests.  Set NODE_ENV=test so it doesn't write to the primary DB (you will get a warning if you don't).  Merged in with latest changes from master.

**Review by debasishbsws — APPROVED** [review]
Fine by me

**Comment by ignoreintuition** [comment]
Let me know if you have any additional feedback

**Pull request merged**
